spring:
  datasource:
    url: jdbc:postgresql://github-cdk-databaseinstanceaa8a5fde-dxfs78eo1x4l.cwj6aay4gbts.us-east-1.rds.amazonaws.com:5432/githubdb?sslmode=verify-full&sslrootcert=/app/global-bundle.pem
    username: postgres
    password: githubPass123

  jpa:
    hibernate:
      ddl-auto: update

app:
  security:
    oauth2:
      enabled: false

logging:
  level:
    org.springframework.security: INFO
