spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:github_pull_requests}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://Github-Keycl-A5slveB416N3-565620607.us-east-1.elb.amazonaws.com/realms/Github}

app:
  security:
    oauth2:
      enabled: ${APP_SECURITY_OAUTH2_ENABLED:true}

logging:
  level:
    org.springframework.security: INFO
