apiVersion: v1
kind: ConfigMap
metadata:
  name: github-pullrequest-ms-config
  labels:
    app: github-pullrequest-ms
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "github_pullrequest_db"
  SERVER_PORT: "8080"
  APP_SECURITY_OAUTH2_ENABLED: "true"
  JWT_ISSUER_URI: "http://Github-Keycl-A5slveB416N3-565620607.us-east-1.elb.amazonaws.com/realms/Github"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
