/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.smithy.g.pullrequest.server.pullrequest.api;

import com.smithy.g.pullrequest.server.pullrequest.model.BadRequestErrorResponseContent;
import java.math.BigDecimal;
import com.smithy.g.pullrequest.server.pullrequest.model.ConflictErrorResponseContent;
import com.smithy.g.pullrequest.server.pullrequest.model.CreatePullRequestBody;
import com.smithy.g.pullrequest.server.pullrequest.model.CreatePullRequestCommentBody;
import com.smithy.g.pullrequest.server.pullrequest.model.ForbiddenErrorResponseContent;
import com.smithy.g.pullrequest.server.pullrequest.model.InternalServerErrorResponseContent;
import com.smithy.g.pullrequest.server.pullrequest.model.ListPullRequestCommentsBody;
import com.smithy.g.pullrequest.server.pullrequest.model.ListPullRequestsBody;
import com.smithy.g.pullrequest.server.pullrequest.model.MergePullRequestBody;
import com.smithy.g.pullrequest.server.pullrequest.model.NotFoundErrorResponseContent;
import com.smithy.g.pullrequest.server.pullrequest.model.PrStatus;
import com.smithy.g.pullrequest.server.pullrequest.model.PullRequestCommentDTO;
import com.smithy.g.pullrequest.server.pullrequest.model.PullRequestDTO;
import com.smithy.g.pullrequest.server.pullrequest.model.PullRequestMergeabilityDTO;
import com.smithy.g.pullrequest.server.pullrequest.model.ReviewPullRequestBody;
import com.smithy.g.pullrequest.server.pullrequest.model.UnauthorizedErrorResponseContent;
import com.smithy.g.pullrequest.server.pullrequest.model.UnprocessableEntityErrorResponseContent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "v1", description = "the v1 API")
public interface V1Api {

    default V1ApiDelegate getDelegate() {
        return new V1ApiDelegate() {};
    }

    /**
     * POST /v1/repos/{owner}/{repo}/pulls
     * Crea un pull request entre dos ramas. RF07.1
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param createPullRequestBody  (required)
     * @return CreatePullRequest 201 response (status code 201)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or ConflictError 409 response (status code 409)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "createPullRequest",
        description = "Crea un pull request entre dos ramas. RF07.1",
        responses = {
            @ApiResponse(responseCode = "201", description = "CreatePullRequest 201 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PullRequestDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "409", description = "ConflictError 409 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConflictErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/repos/{owner}/{repo}/pulls",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<PullRequestDTO> createPullRequest(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "CreatePullRequestBody", description = "", required = true) @Valid @RequestBody CreatePullRequestBody createPullRequestBody
    ) {
        return getDelegate().createPullRequest(owner, repo, createPullRequestBody);
    }


    /**
     * POST /v1/repos/{owner}/{repo}/pulls/{prNumber}/comments
     * Agrega un comentario general o por linea a un pull request.
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param prNumber  (required)
     * @param createPullRequestCommentBody  (required)
     * @return CreatePullRequestComment 201 response (status code 201)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "createPullRequestComment",
        description = "Agrega un comentario general o por linea a un pull request.",
        responses = {
            @ApiResponse(responseCode = "201", description = "CreatePullRequestComment 201 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PullRequestCommentDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/repos/{owner}/{repo}/pulls/{prNumber}/comments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<PullRequestCommentDTO> createPullRequestComment(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "prNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("prNumber") BigDecimal prNumber,
        @Parameter(name = "CreatePullRequestCommentBody", description = "", required = true) @Valid @RequestBody CreatePullRequestCommentBody createPullRequestCommentBody
    ) {
        return getDelegate().createPullRequestComment(owner, repo, prNumber, createPullRequestCommentBody);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/pulls/{prNumber}
     * Obtiene el detalle de un pull request.
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param prNumber  (required)
     * @return GetPullRequest 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getPullRequest",
        description = "Obtiene el detalle de un pull request.",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetPullRequest 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PullRequestDTO.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/pulls/{prNumber}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PullRequestDTO> getPullRequest(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "prNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("prNumber") BigDecimal prNumber
    ) {
        return getDelegate().getPullRequest(owner, repo, prNumber);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/pulls/{prNumber}/mergeability
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param prNumber  (required)
     * @return GetPullRequestMergeability 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "getPullRequestMergeability",
        description = "Evalua conflictos y mergeabilidad antes de merge. RF07.3",
        responses = {
            @ApiResponse(responseCode = "200", description = "GetPullRequestMergeability 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PullRequestMergeabilityDTO.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/pulls/{prNumber}/mergeability",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PullRequestMergeabilityDTO> getPullRequestMergeability(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "prNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("prNumber") BigDecimal prNumber
    ) {
        return getDelegate().getPullRequestMergeability(owner, repo, prNumber);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/pulls/{prNumber}/comments
     * Lista comentarios de un pull request.
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param prNumber  (required)
     * @return ListPullRequestComments 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "listPullRequestComments",
        description = "Lista comentarios de un pull request.",
        responses = {
            @ApiResponse(responseCode = "200", description = "ListPullRequestComments 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListPullRequestCommentsBody.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/pulls/{prNumber}/comments",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ListPullRequestCommentsBody> listPullRequestComments(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "prNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("prNumber") BigDecimal prNumber
    ) {
        return getDelegate().listPullRequestComments(owner, repo, prNumber);
    }


    /**
     * GET /v1/repos/{owner}/{repo}/pulls
     * Lista los pull requests del repositorio. RF07
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param status  (optional)
     * @return ListPullRequests 200 response (status code 200)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "listPullRequests",
        description = "Lista los pull requests del repositorio. RF07",
        responses = {
            @ApiResponse(responseCode = "200", description = "ListPullRequests 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListPullRequestsBody.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/repos/{owner}/{repo}/pulls",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ListPullRequestsBody> listPullRequests(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "status", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) PrStatus status
    ) {
        return getDelegate().listPullRequests(owner, repo, status);
    }


    /**
     * POST /v1/repos/{owner}/{repo}/pulls/{prNumber}/merge
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param prNumber  (required)
     * @param mergePullRequestBody  (required)
     * @return MergePullRequest 200 response (status code 200)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or ConflictError 409 response (status code 409)
     *         or UnprocessableEntityError 422 response (status code 422)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "mergePullRequest",
        description = "Ejecuta merge de un pull request aprobado y sin conflictos.",
        responses = {
            @ApiResponse(responseCode = "200", description = "MergePullRequest 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PullRequestDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "409", description = "ConflictError 409 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConflictErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "422", description = "UnprocessableEntityError 422 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnprocessableEntityErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/repos/{owner}/{repo}/pulls/{prNumber}/merge",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<PullRequestDTO> mergePullRequest(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "prNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("prNumber") BigDecimal prNumber,
        @Parameter(name = "MergePullRequestBody", description = "", required = true) @Valid @RequestBody MergePullRequestBody mergePullRequestBody
    ) {
        return getDelegate().mergePullRequest(owner, repo, prNumber, mergePullRequestBody);
    }


    /**
     * PATCH /v1/repos/{owner}/{repo}/pulls/{prNumber}/review
     * Aprueba o solicita cambios en un pull request. RF07.2
     *
     * @param owner  (required)
     * @param repo  (required)
     * @param prNumber  (required)
     * @param reviewPullRequestBody  (required)
     * @return ReviewPullRequest 200 response (status code 200)
     *         or BadRequestError 400 response (status code 400)
     *         or UnauthorizedError 401 response (status code 401)
     *         or ForbiddenError 403 response (status code 403)
     *         or NotFoundError 404 response (status code 404)
     *         or InternalServerError 500 response (status code 500)
     */
    @Operation(
        operationId = "reviewPullRequest",
        description = "Aprueba o solicita cambios en un pull request. RF07.2",
        responses = {
            @ApiResponse(responseCode = "200", description = "ReviewPullRequest 200 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PullRequestDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "BadRequestError 400 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BadRequestErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "401", description = "UnauthorizedError 401 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnauthorizedErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "403", description = "ForbiddenError 403 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ForbiddenErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "NotFoundError 404 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotFoundErrorResponseContent.class))
            }),
            @ApiResponse(responseCode = "500", description = "InternalServerError 500 response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InternalServerErrorResponseContent.class))
            })
        },
        security = {
            @SecurityRequirement(name = "smithy.api.httpBearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/v1/repos/{owner}/{repo}/pulls/{prNumber}/review",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<PullRequestDTO> reviewPullRequest(
        @Pattern(regexp = "^[a-zA-Z0-9_-]+$") @Size(min = 3, max = 50) @Parameter(name = "owner", description = "", required = true, in = ParameterIn.PATH) @PathVariable("owner") String owner,
        @Pattern(regexp = "^[a-zA-Z0-9._-]+$") @Size(min = 1, max = 150) @Parameter(name = "repo", description = "", required = true, in = ParameterIn.PATH) @PathVariable("repo") String repo,
        @Parameter(name = "prNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("prNumber") BigDecimal prNumber,
        @Parameter(name = "ReviewPullRequestBody", description = "", required = true) @Valid @RequestBody ReviewPullRequestBody reviewPullRequestBody
    ) {
        return getDelegate().reviewPullRequest(owner, repo, prNumber, reviewPullRequestBody);
    }

}
